#!/bin/bash
set -euo pipefail

# ──────────────────────────────────────────────
# 📁 CREATE A NEW R PROJECT
# Sets up a clean folder structure for an R analysis project
# with renv for package management and git for AI agents.
# ──────────────────────────────────────────────

REPO_URL="https://raw.githubusercontent.com/dca-python/agentic-r/main"

# ── Helper: offer to run the next script ──
offer_next() {
    local prompt="$1"
    local script_url="$2"
    local answer
    read -rp "$prompt (y/n): " answer
    if [[ "$answer" =~ ^[Yy] ]]; then
        echo ""
        /bin/bash -c "$(curl -fsSL "$script_url")"
        exit 0
    fi
}

clear
echo "=========================================="
echo "📁 NEW R PROJECT SETUP"
echo "=========================================="
echo ""

# ── Ask for project name (default: my-analysis) ──
DEFAULT_NAME="my-analysis"
read -rp "Project name [$DEFAULT_NAME]: " PROJECT_NAME
PROJECT_NAME="${PROJECT_NAME:-$DEFAULT_NAME}"

# Clean the name: lowercase, replace spaces with dashes, remove special characters
PROJECT_NAME=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g')

if [[ -z "$PROJECT_NAME" ]]; then
    PROJECT_NAME="$DEFAULT_NAME"
fi

# Default location: user's home directory
PROJECT_DIR="$HOME/$PROJECT_NAME"

if [[ -d "$PROJECT_DIR" ]]; then
    echo "⚠️  A folder called '$PROJECT_NAME' already exists at $PROJECT_DIR."
    echo "   Pick a different name or delete the existing folder first."
    exit 1
fi

echo ""
echo "Creating project at: $PROJECT_DIR"
echo ""

# ── Create folder structure ──
mkdir -p "$PROJECT_DIR"
mkdir -p "$PROJECT_DIR/data/raw"
mkdir -p "$PROJECT_DIR/data/processed"
mkdir -p "$PROJECT_DIR/output/figures"
mkdir -p "$PROJECT_DIR/output/tables"
mkdir -p "$PROJECT_DIR/src"

echo "  📂 data/raw/         ← put your original data files here (CSVs, Excel, etc.)"
echo "  📂 data/processed/   ← cleaned/transformed data goes here"
echo "  📂 output/figures/   ← plots and visualizations"
echo "  📂 output/tables/    ← exported tables and summaries"
echo "  📂 src/              ← your R scripts"

# ── Create starter R scripts ──
# These use mtcars so they run out of the box — replace with your own data later.

cat > "$PROJECT_DIR/src/01_load_data.R" << 'RSCRIPT'
# ──────────────────────────────────────────────
# 01_load_data.R
# Load and inspect raw data
# ──────────────────────────────────────────────

library(tidyverse)

# Demo: using mtcars. Replace with your own data, e.g.:
#   df <- read_csv("data/raw/your_file.csv")
df <- mtcars |>
  rownames_to_column("car")

glimpse(df)
summary(df)
RSCRIPT

cat > "$PROJECT_DIR/src/02_clean_data.R" << 'RSCRIPT'
# ──────────────────────────────────────────────
# 02_clean_data.R
# Clean and transform data
# ──────────────────────────────────────────────

library(tidyverse)

source("src/01_load_data.R")

df_clean <- df |>
  mutate(
    cyl = factor(cyl),
    am  = factor(am, labels = c("Automatic", "Manual"))
  ) |>
  arrange(desc(mpg))

glimpse(df_clean)

# Save processed data
# write_csv(df_clean, "data/processed/cleaned_data.csv")
RSCRIPT

cat > "$PROJECT_DIR/src/03_analysis.R" << 'RSCRIPT'
# ──────────────────────────────────────────────
# 03_analysis.R
# Main analysis
# ──────────────────────────────────────────────

library(tidyverse)

source("src/02_clean_data.R")

# Summary by cylinder count
df_clean |>
  group_by(cyl) |>
  summarise(n = n(), mpg = mean(mpg), hp = mean(hp), .groups = "drop") |>
  print()

# Scatter plot: MPG vs Weight
p1 <- ggplot(df_clean, aes(wt, mpg, colour = cyl)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Fuel Economy vs Weight", x = "Weight (1000 lbs)", y = "MPG") +
  theme_minimal()

print(p1)

# Save plot
dir.create("output/figures", recursive = TRUE, showWarnings = FALSE)
ggsave("output/figures/mpg_vs_weight.png", p1, width = 8, height = 5)
RSCRIPT

echo ""

# ── Create .gitignore ──
cat > "$PROJECT_DIR/.gitignore" << 'GITIGNORE'
# R
.Rhistory
.RData
.Rproj.user

# renv (track the lockfile, not the library)
renv/library/
renv/staging/
renv/sandbox/

# Data (track code, not data — add exceptions as needed)
data/raw/*
data/processed/*
!data/raw/.gitkeep
!data/processed/.gitkeep

# Output (regenerated by scripts)
output/

# OS
.DS_Store
GITIGNORE

# Keep empty directories in git
touch "$PROJECT_DIR/data/raw/.gitkeep"
touch "$PROJECT_DIR/data/processed/.gitkeep"

echo "  📄 .gitignore         ← keeps data and output out of git"

# ── Bootstrap renv (R package management) ──
if command -v Rscript &> /dev/null; then
    echo ""
    echo "📦 Setting up renv (package management)..."

    # Install renv itself if missing
    Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv', repos = 'https://cloud.r-project.org')" 2>/dev/null || true

    # Initialise renv in the project (bare = TRUE: no auto-discovery, we'll add packages explicitly)
    Rscript -e "setwd('$PROJECT_DIR'); renv::init(bare = TRUE)" 2>/dev/null || true

    # Install tidyverse into the project library and snapshot
    echo "  Installing tidyverse into project library (one-time, may take a minute)..."
    Rscript -e "setwd('$PROJECT_DIR'); renv::install('tidyverse'); renv::snapshot()" 2>/dev/null || {
        echo "  ⚠️  renv setup had an issue. You can fix it later: renv::restore()"
    }

    echo "  ✅ renv ready — packages are tracked in renv.lock"
else
    echo "⚠️  Rscript not found. Run setup.sh first, then re-run this script."
fi

echo ""

# ── Create CLAUDE.md (AI agent instructions) ──
cat > "$PROJECT_DIR/CLAUDE.md" << 'CLAUDEMD'
# Project conventions

This is an R analysis project. Scripts live in `src/` and are numbered in execution order.

## Package management

This project uses **renv** for dependency management. When installing or removing R packages:

- Install: `renv::install("package_name")`
- Remove: `renv::remove("package_name")`
- **Always run `renv::snapshot()` after installing or removing packages** so the lockfile stays current.
- Never use `install.packages()` directly — it bypasses renv tracking.

## Running scripts

Scripts use relative paths from the project root. Run them with:
```
Rscript src/03_analysis.R
```
Or source them in an R session with the working directory set to the project root.
CLAUDEMD

echo "  📄 CLAUDE.md          ← tells AI agents how this project works"

# ── Initialise git repo (required by AI agents like Claude Code) ──
git -C "$PROJECT_DIR" init -q
git -C "$PROJECT_DIR" add -A
git -C "$PROJECT_DIR" commit -q -m "Initial project scaffold"
echo "  📦 git repo initialised with first commit"

# ── Create a README for the project ──
cat > "$PROJECT_DIR/README.md" << 'README'
# My Analysis

> Replace this section with your research question or analysis goal.

## If you're coming from RStudio

This project is set up for VS Code + AI agents instead of RStudio. A few things work differently.

### Running code

| RStudio | Here |
|---|---|
| Click **Run** or Cmd+Enter | Same — Cmd+Enter works (if you ran `rstudio-feel.sh`) |
| Click **Source** | In the terminal: `Rscript src/03_analysis.R` |
| Type in the Console pane | Type in the **Terminal** pane (the R session at the bottom) |

### Installing packages

In RStudio you'd click the **Install** button or type `install.packages("sf")`. Here, this project uses **renv** so that your packages are tracked and reproducible.

```r
# Instead of install.packages("sf"), do:
renv::install("sf")
renv::snapshot()   # saves it to the lockfile
```

Or just tell your AI agent "I need the sf package" — it knows what to do.

**Why?** Without renv, there's no record of what packages your project needs. If you share the code or come back in six months, things break. renv is like a grocery list — it writes down exactly what you installed so anyone (including future-you) can recreate it with `renv::restore()`.

### The `<-` arrow and `|>` pipe

If you ran `rstudio-feel.sh`, these work the same as RStudio:
- **Alt + -** types `<-`
- **Ctrl + Shift + M** types `|>`

### Plots

Plots appear in a side panel, similar to RStudio's Plots tab. This is handled by the `httpgd` package (installed by `rstudio-feel.sh`).

### Environment / variables

The **R Workspace Viewer** in the sidebar shows your loaded variables, similar to RStudio's Environment pane (top-right). Click the R icon in the left sidebar to see it.

## Project structure

```
src/               ← R scripts, numbered in execution order
data/raw/          ← original data files (CSVs, Excel, etc.)
data/processed/    ← cleaned data
output/figures/    ← plots
output/tables/     ← exported tables
renv.lock          ← package versions (like a grocery list for R packages)
CLAUDE.md          ← instructions for AI agents
```

## Scripts

Run them in order, or just run the last one (it sources the others):

1. `src/01_load_data.R` — Load and inspect raw data
2. `src/02_clean_data.R` — Clean and transform
3. `src/03_analysis.R` — Main analysis and plots

They currently use the built-in `mtcars` dataset as a demo. Replace with your own data.

## What is git and why is it here?

Git tracks changes to your code — like "Track Changes" in Word, but for scripts. It's here because AI agents (Claude Code, Gemini CLI) require it to work. You don't need to learn git commands; the AI agent handles it. But if you're curious:

- `git status` — see what changed
- `git log --oneline` — see the history of changes

Your **data files and output are not tracked** by git (see `.gitignore`) — only your code is.
README

# Fix the project name in the README title
sed -i '' "s/^# My Analysis$/# $PROJECT_NAME/" "$PROJECT_DIR/README.md"

echo "  📄 README.md           ← how this project works (read this first)"
echo ""

echo ""
echo "=========================================="
echo "🎉 PROJECT CREATED!"
echo "=========================================="
echo ""
echo "To start working:"
echo "  1. Open VS Code"
echo "  2. Go to File → Open Folder → select '$PROJECT_NAME' in your home directory"
echo "  3. Open src/01_load_data.R and start editing"
echo ""
echo "💡 Tip: Put your data files (CSV, Excel, etc.) into the data/raw/ folder."
echo ""

# Open the project in VS Code
if command -v code &> /dev/null; then
    read -rp "Open this project in VS Code now? (y/n): " OPEN_VSCODE
    if [[ "$OPEN_VSCODE" =~ ^[Yy] ]]; then
        code "$PROJECT_DIR"
    fi
fi

echo ""
echo "------------------------------------------"
echo ""
echo "What's next?"
echo ""
offer_next "Make VS Code feel like RStudio?" "$REPO_URL/rstudio-feel.sh"
echo ""
offer_next "Run the full setup (Homebrew, R, VS Code, Node.js)?" "$REPO_URL/setup.sh"
echo ""
